# Generated by Django 2.1.4 on 2019-05-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo_item', models.CharField(max_length=150)),
                ('descricao', models.CharField(max_length=3000)),
                ('referencia', models.CharField(max_length=150)),
                ('preco', models.FloatField()),
                ('image', models.ImageField(upload_to='static/blogue/img')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
