# Generated by Django 2.1.4 on 2019-06-03 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0002_blog_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.SlugField(max_length=150),
        ),
    ]
