# Generated by Django 2.1.4 on 2019-06-03 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0005_auto_20190603_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hashtags',
            field=models.CharField(max_length=250),
        ),
    ]
