# Generated by Django 2.1.4 on 2019-06-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0006_auto_20190603_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='hashtags',
            field=models.SlugField(max_length=250),
        ),
    ]
