# Generated by Django 2.1.4 on 2019-06-04 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0009_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='hashtags',
        ),
    ]
