# Generated by Django 2.1.4 on 2019-06-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0010_remove_blog_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_post',
            field=models.ManyToManyField(to='blogue.blog'),
        ),
    ]
