# Generated by Django 2.1.4 on 2019-06-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0011_tag_tag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_post',
            field=models.ManyToManyField(blank=True, null=True, to='blogue.blog'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
    ]
