# Generated by Django 2.1.4 on 2019-06-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogue', '0012_auto_20190605_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_post',
            field=models.ManyToManyField(blank=True, to='blogue.blog'),
        ),
    ]
